Repository con/tinuous, pull requests merged in 2021-06, with the labels that each got.

#66 Reorganize code
  src/tinuous/__main__.py
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/config.py
  src/tinuous/github.py
  src/tinuous/travis.py
  src/tinuous/util.py
Labels: internal

#68 Fill in `{commit}` for Travis PR builds by querying GitHub
  README.rst
  src/tinuous/__main__.py
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/config.py
  src/tinuous/github.py
  src/tinuous/travis.py
  src/tinuous/util.py
Labels: minor

#71 Better `{commit}` lookup for Travis builds
  src/tinuous/github.py
  src/tinuous/travis.py
Labels: patch

#76 Add "until:" config setting
  README.rst
  src/tinuous/__main__.py
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/config.py
  src/tinuous/github.py
  src/tinuous/travis.py
Labels: minor

#73 Add `{job_index}`, `{job_env}`, and `{job_env_hash}` placeholders
  README.rst
  src/tinuous/appveyor.py
  src/tinuous/github.py
  src/tinuous/travis.py
  src/tinuous/util.py
Labels: minor

#81 Add --version option
  src/tinuous/__main__.py
Labels: minor

#79 Don't expand unused vars
  src/tinuous/util.py
  test/test_util.py
  tox.ini
Labels: patch

#80 Allow specifying GitHub workflow inclusions & exclusions with regexes
  README.rst
  src/tinuous/base.py
  src/tinuous/config.py
  src/tinuous/github.py
  test/test_config.py
  tox.ini
Labels: minor

#87 Skip GitHub logs that return 410
  src/tinuous/github.py
Labels: patch

#86 Add "Produced by tinuous" message to Datalad commit messages
  src/tinuous/__main__.py
  src/tinuous/util.py
Labels: minor

#89 Add test run with Datalad
  .github/workflows/inception-test.yml
Labels: tests

#91 Retry downloads interrupted by connnection resets
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/github.py
  src/tinuous/travis.py
  src/tinuous/util.py
Labels: patch

#95 Add "manual" event type
  README.rst
  src/tinuous/base.py
  src/tinuous/github.py
  src/tinuous/travis.py
Labels: minor

#99 Doc fix: Custom placeholders don't have to be defined in order any more
  README.rst
Labels: documentation

#96 Make the "types" setting optional
  README.rst
  src/tinuous/config.py
Labels: minor

#97 [BREAKING] Replace `{type_id}` for releases with `{release_tag}`
  README.rst
  src/tinuous/github.py
Labels: minor

#98 [BREAKING] Redo path specifications
  README.rst
  src/tinuous/__main__.py
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/config.py
  src/tinuous/github.py
  src/tinuous/travis.py
  test/test_config.py
Labels: minor

#100 Rename state file; update state file after each CI system finishes
  README.rst
  src/tinuous/__main__.py
  src/tinuous/state.py
  test/test_state.py
Labels: minor

#101 [BREAKING] Rename default config file to `tinuous.yaml`
  README.rst
  src/tinuous/__main__.py
Labels: minor

#105 DOC: a more kosher casing of DataLad
  README.rst
Labels: documentation

#102 Allow `since` setting to override state file if newer
  README.rst
  src/tinuous/state.py
  test/test_state.py
Labels: minor, release

#103 Update config file name in inception-test workflow
  .github/workflows/inception-test.yml
Labels: tests

#106 Document how to integrate with cron
  README.rst
Labels: documentation

#107 Add Anaconda badge and installation command
  README.rst
Labels: documentation

#115 Fix README formatting
  README.rst
Labels: documentation

#108 Update GitHub token regex in sample config
  README.rst
Labels: documentation

#109 Add docstring to `__init__.py`
  src/tinuous/__init__.py
Labels: documentation

#111 Test removeprefix
  test/test_util.py
Labels: tests

#116 Delay opening of config file to actual command execution
  src/tinuous/__main__.py
Labels: patch

#112 Test WorkflowSpec.match()
  src/tinuous/base.py
  src/tinuous/github.py
  test/test_base.py
Labels: tests

#110 Specify that the regexes are Python regexes and link to the Python docs
  README.rst
Labels: documentation

#114 Add `{timestamp}` and `{timestamp_local}` placeholders
  README.rst
  src/tinuous/appveyor.py
  src/tinuous/base.py
  src/tinuous/github.py
  src/tinuous/travis.py
  src/tinuous/util.py
  test/test_util.py
Labels: minor

#117 Sleep when search rate limit reached
  src/tinuous/github.py
Labels: patch

#121 Save changes in DataLad if only the statefile was modified
  src/tinuous/__main__.py
  src/tinuous/state.py
  test/test_state.py
Labels: patch

#120 Recognize "canceled" status
  src/tinuous/base.py
Labels: patch, release

#123 Escape branch names, workflow names, and Appveyor job envs with percent encoding
  README.rst
  src/tinuous/base.py
  src/tinuous/util.py
  test/test_util.py
Labels: minor

#122 Minor README tweaks
  README.rst
Labels: documentation
